/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <poll.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>
/* Header for class com_llp_accgpiodemo_NativeGpio */

#ifndef _Included_com_llp_accgpiodemo_NativeGpio
#define _Included_com_llp_accgpiodemo_NativeGpio
#ifdef __cplusplus
extern "C" {
#endif
int read_gpio(char *path, void (*callback)(int));
#ifdef __cplusplus
}
#endif
#endif
